### ISSUE TITLE
ts-node error

### ISSUE THREAD

**Issue by amenome** [consumet/api.consumet.org#366]
### Describe the bug

Docker container from fresh build fails to start

### Steps to reproduce

Assuming you have the git repo cloned:
```
cd ../consumet-api
git pull

docker rm -f local_consumet
docker container prune -f
docker build -t consumet-api .

docker run -p 3000:3000 --name local_consumet consumet-api
```

### Expected behavior

Container should start.

### Actual behavior

Error message follows:

```
> api.consumet.org@1.0.0 start
> ts-node src/main.ts

/home/nodejs/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/routes/anime/9anime.ts(112,35): error TS2341: Property 'ev' is private and only accessible within class 'NineAnime'.
src/routes/anime/9anime.ts(115,35): error TS2551: Property 'searchVrf' does not exist on type 'NineAnime'. Did you mean 'search'?
src/routes/anime/9anime.ts(118,35): error TS2339: Property 'decrypt' does not exist on type 'NineAnime'.
src/routes/anime/9anime.ts(121,35): error TS2339: Property 'vizcloud' does not exist on type 'NineAnime'.
src/routes/anime/9anime.ts(124,35): error TS2339: Property 'customRequest' does not exist on type 'NineAnime'.

    at createTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/nodejs/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/home/nodejs/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2341, 2551, 2339, 2339, 2339 ]
}
npm notice
npm notice New minor version of npm available! 9.2.0 -> 9.6.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
npm notice Run `npm install -g npm@9.6.2` to update!
npm notice
```

**Comment by amenome** [comment]
This is fixed by this PR:

https://github.com/consumet/api.consumet.org/pull/364
