### ISSUE TITLE
fmovies.ts and marin.ts commits break consumet docker

### ISSUE THREAD

**Issue by amenome** [consumet/api.consumet.org#382]
### Describe the bug

Reverting latest fmovies.ts and marin.ts is required to run docker

### Steps to reproduce

Assuming you have the repo cloned:

```
cd ../consumet-api
git pull

docker rm -f local_consumet
docker container prune -f
docker build -t consumet-api .

docker run -p 3000:3000 --name local_consumet consumet-api
```

### Expected behavior

Container should start.

### Actual behavior

Before reverting marin.ts:
```
> api.consumet.org@1.0.0 start
> ts-node src/main.ts

/home/nodejs/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/routes/anime/marin.ts(65,12): error TS2554: Expected 2 arguments, but got 1.

    at createTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/nodejs/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/home/nodejs/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2554 ]
}
npm notice
npm notice New minor version of npm available! 9.2.0 -> 9.6.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
npm notice Run `npm install -g npm@9.6.2` to update!
npm notice
```

Before reverting fmovies.ts:
```
> api.consumet.org@1.0.0 start
> ts-node src/main.ts

/home/nodejs/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/routes/movies/fmovies.ts(15,5): error TS2554: Expected 0-2 arguments, but got 3.

    at createTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/nodejs/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/home/nodejs/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2554 ]
}
npm notice
npm notice New minor version of npm available! 9.2.0 -> 9.6.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
npm notice Run `npm install -g npm@9.6.2` to update!
npm notice
```

**Comment by TDanks2000** [comment]
These errors are because you have not got the latest version of consumet.ts from the repo

**Comment by amenome** [comment]
> These errors are because you have not got the latest version of consumet.ts from the repo

I didn't check out the consumet.ts repo - I'm just cloning the consumet-api repo.

The repo has a yarn.lock that points to 1.4.16 of consumet.ts.  That seems to be the latest version of that repo (although not head).

Maybe these changes should have waited until there was a new version cut of consumet.ts?

**Comment by TDanks2000** [comment]
no because the official api use's the repo link instead of npm to get the releases

**Comment by TDanks2000** [comment]
i have made a new update please use that

**Comment by amenome** [comment]
Okay, so this should get fixed as soon as the bot updates yarn.lock.  Not sure how that gets scheduled, but I'll test as soon as that's available.

**Comment by amenome** [comment]
This pull request will fix this issue: https://github.com/consumet/api.consumet.org/pull/383/files
