### ISSUE TITLE
Getting continuous error on getting links 

### ISSUE THREAD

**Issue by zues-adi** [consumet/api.consumet.org#469]
### Describe the bug

No response

### Steps to reproduce

Request the link for a movie or episode using tmdb meta

### Expected behavior

This should provide links for the id

### Actual behavior

{"level":40,"time":1690022745923,"pid":8,"hostname":"169.254.16.169","reqId":"req-1g","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at Reply.send (/var/task/node_modules/fastify/lib/reply.js:127:26)\n    at /vercel/path0/src/routes/meta/tmdb.ts:55:27\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/task/src/routes/meta/tmdb.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","code":"FST_ERR_REP_ALREADY_SENT","name":"FastifyError","statusCode":500},"msg":"Reply already sent"}

Getting following error in logs

**Comment by Compound-Z** [comment]
i got the same error, any solution found?

**Comment by Cimasearch** [comment]
Same problem! Sometimes no links is working..

**Comment by Blixtdraken** [comment]
I am ahving the same issue when trying to get info from gogoanime, any sulotion yet?

**Comment by rafaeuw** [comment]
Same issue here
