### ISSUE TITLE
mangakakalot.ts expects 2 arguments, but got 1.

### ISSUE THREAD

**Issue by shibotto** [consumet/api.consumet.org#645]
### Describe the bug

Can't deploy consumet API after https://github.com/consumet/consumet.ts/commit/5e2ab3e72385a26de4c6049507cc7d85651fb08c

### Steps to reproduce

Try to deploy

### Expected behavior

Deploy

### Actual behavior

Does not deploy

### Additional context

```
> api.consumet.org@1.0.0 start
> ts-node src/main.ts

/home/nodejs/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/routes/manga/mangakakalot.ts(50,10): error TS2554: Expected 2 arguments, but got 1.
    at createTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/nodejs/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/nodejs/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/nodejs/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .ts] (/home/nodejs/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  diagnosticCodes: [ 2554 ]
}
==> Exited with status 1
```

**Comment by riimuru** [comment]
fixed as of https://github.com/consumet/api.consumet.org/pull/640
